services:
  jupyter:
    container_name: jupyter
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - AWS_CLI=${AWS_CLI}
        - AZURE_CLI=${AZURE_CLI}
        - GCP_CLI=${GCP_CLI}
        - DOCKER_CLI=${DOCKER_CLI}
        - TERRAFORM_CLI=${TERRAFORM_CLI}
        - HELM_CLI=${HELM_CLI}
        - KUBECTL_CLI=${KUBECTL_CLI}
        - ANSIBLE_CLI=${ANSIBLE_CLI}
    env_file:
      - .env
    userns_mode: host
    ports:
      - target: 8888
        published: 8888
        protocol: tcp
        mode: host
    volumes:
      - ${PWD}/notebook:/notebook
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /notebook
    entrypoint:
      - /usr/local/bin/jupyter
    command:
      - lab
      - --port=8888
      - --ip=0.0.0.0
      - --notebook-dir=/notebook
      - --allow-root
      - --no-browser
      - --NotebookApp.token=''
    networks:
      - jupyter

networks:
  jupyter:
    driver: bridge
