version: "3"

services:
  jupyter:
    container_name: jupyter
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - AWS_CLI=true
        - AZURE_CLI=true
        - GCP_CLI=true
        - DOCKER_CLI=true
        - TERRAFORM_CLI=true
        - HELM_CLI=true
    userns_mode: host
    ports:
      - 8888:8888
    volumes:
      - ${PWD}/notebook:/notebook
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /notebook
    entrypoint:
      - /usr/local/bin/jupyter
    command:
      - lab
      - --port=8888
      - --ip=0.0.0.0
      - --notebook-dir=/notebook
      - --allow-root
      - --no-browser
      - --NotebookApp.token=''
    networks:
      - jupyter

networks:
  jupyter:
    driver: bridge
